language: php

php: [5.6, nightly]

matrix:
    allow_failures:
        - php: nightly

before_script:
  - composer install --prefer-source --no-interaction --no-progress
  - export PATH=./vendor/bin:$PATH

script:
  - phpunit -v --coverage-clover=coverage.clover

#after_script:
#  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'